apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jnognet@gmail.com
    privateKeySecretRef:
      name: letsencrypt-privatekey-secret
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
